from django.contrib.auth.models import Group
from django.contrib.contenttypes.models import ContentType
from nautobot.users.models import ObjectPermission

GROUPS = {g.name: g for g in Group.objects.all()}

DELTA = [
    {
        "name": "vpn_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpn"],
    },
    {
        "name": "vpn_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpn"],
    },
    {
        "name": "vpn_vac",
        "actions": ["view", "add", "change"],
        "groups": [GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpn"],
    },
    {
        "name": "vpn_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpn"],
    },
    {
        "name": "vpn_tunnel_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpntunnel"],
    },
    {
        "name": "vpn_tunnel_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpntunnel"],
    },
    {
        "name": "vpn_tunnel_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpntunnel"],
    },
    {
        "name": "vpn_tunnel_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpntunnel"],
    },
    {
        "name": "vpn_tunnel_endpoint_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpntunnelendpoint"],
    },
    {
        "name": "vpn_tunnel_endpoint_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpntunnelendpoint"],
    },
    {
        "name": "vpn_tunnel_endpoint_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpntunnelendpoint"],
    },
    {
        "name": "vpn_tunnel_endpoint_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpntunnelendpoint"],
    },
    {
        "name": "vpn_profile_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpnprofile"],
    },
    {
        "name": "vpn_profile_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpnprofile"],
    },
    {
        "name": "vpn_profile_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpnprofile"],
    },
    {
        "name": "vpn_profile_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpnprofile"],
    },
    {
        "name": "vpn_phase1_policy_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpnphase1policy"],
    },
    {
        "name": "vpn_phase1_policy_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpnphase1policy"],
    },
    {
        "name": "vpn_phase1_policy_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpnphase1policy"],
    },
    {
        "name": "vpn_phase1_policy_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpnphase1policy"],
    },
    {
        "name": "vpn_phase2_policy_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpnphase2policy"],
    },
    {
        "name": "vpn_phase2_policy_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpnphase2policy"],
    },
    {
        "name": "vpn_phase2_policy_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpnphase2policy"],
    },
    {
        "name": "vpn_phase2_policy_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["vpn"],
        "model": ["vpnphase2policy"],
    },
    {
        "name": "controller_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"]],
        "enabled": True,
        "app_label": ["dcim"],
        "model": ["controller"],
    },
    {
        "name": "controller_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["dcim"],
        "model": ["controller"],
    },
    {
        "name": "controller_vac",
        "actions": ["view", "add", "change"],
        "groups": [GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["dcim"],
        "model": ["controller"],
    },
    {
        "name": "controller_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["dcim"],
        "model": ["controller"],
    },
    {
        "name": "virtual_server_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["virtualserver"],
    },
    {
        "name": "virtual_server_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["virtualserver"],
    },
    {
        "name": "virtual_server_vac",
        "actions": ["view", "add", "change"],
        "groups": [GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["virtualserver"],
    },
    {
        "name": "virtual_server_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["virtualserver"],
    },
    {
        "name": "load_balancer_pool_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["loadbalancerpool"],
    },
    {
        "name": "load_balancer_pool_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["loadbalancerpool"],
    },
    {
        "name": "load_balancer_pool_vac",
        "actions": ["view", "add", "change"],
        "groups": [GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["loadbalancerpool"],
    },
    {
        "name": "load_balancer_pool_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["loadbalancerpool"],
    },
    {
        "name": "load_balancer_pool_member_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["loadbalancerpoolmember"],
    },
    {
        "name": "load_balancer_pool_member_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["loadbalancerpoolmember"],
    },
    {
        "name": "load_balancer_pool_member_vac",
        "actions": ["view", "add", "change"],
        "groups": [GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["loadbalancerpoolmember"],
    },
    {
        "name": "load_balancer_pool_member_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["loadbalancerpoolmember"],
    },
    {
        "name": "health_check_monitor_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["healthcheckmonitor"],
    },
    {
        "name": "health_check_monitor_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["healthcheckmonitor"],
    },
    {
        "name": "health_check_monitor_vac",
        "actions": ["view", "add", "change"],
        "groups": [GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["healthcheckmonitor"],
    },
    {
        "name": "health_check_monitor_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["healthcheckmonitor"],
    },
    {
        "name": "certificate_profile_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["certificateprofile"],
    },
    {
        "name": "certificate_profile_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["certificateprofile"],
    },
    {
        "name": "certificate_profile_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["certificateprofile"],
    },
    {
        "name": "certificate_profile_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["load_balancers"],
        "model": ["certificateprofile"],
    },
    {
        "name": "workflow_definition_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["extras"],
        "model": ["approvalworkflowdefinition"],
    },
    {
        "name": "workflow_definition_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["extras"],
        "model": ["approvalworkflowdefinition"],
    },
    {
        "name": "workflow_definition_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["extras"],
        "model": ["approvalworkflowdefinition"],
    },
    {
        "name": "workflow_definition_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["extras"],
        "model": ["approvalworkflowdefinition"],
    },
    {
        "name": "min_max_rule_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["minmaxvalidationrule"],
    },
    {
        "name": "min_max_rule_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["minmaxvalidationrule"],
    },
    {
        "name": "min_max_rule_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["minmaxvalidationrule"],
    },
    {
        "name": "min_max_rule_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["minmaxvalidationrule"],
    },
    {
        "name": "regex_rule_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["regularexpressionvalidationrule"],
    },
    {
        "name": "regex_rule_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["regularexpressionvalidationrule"],
    },
    {
        "name": "regex_rule_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["regularexpressionvalidationrule"],
    },
    {
        "name": "regex_rule_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["regularexpressionvalidationrule"],
    },
    {
        "name": "required_rule_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["requiredvalidationrule"],
    },
    {
        "name": "required_rule_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["requiredvalidationrule"],
    },
    {
        "name": "required_rule_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["requiredvalidationrule"],
    },
    {
        "name": "required_rule_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["requiredvalidationrule"],
    },
    {
        "name": "unique_rule_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["uniquevalidationrule"],
    },
    {
        "name": "unique_rule_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["uniquevalidationrule"],
    },
    {
        "name": "unique_rule_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["uniquevalidationrule"],
    },
    {
        "name": "unique_rule_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["uniquevalidationrule"],
    },
    {
        "name": "data_compliance_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["datacompliance"],
    },
    {
        "name": "data_compliance_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["datacompliance"],
    },
    {
        "name": "data_compliance_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["datacompliance"],
    },
    {
        "name": "data_compliance_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["data_validation"],
        "model": ["datacompliance"],
    },
    {
        "name": "object_metadata_v",
        "actions": ["view"],
        "groups": [GROUPS["Nautobot User"], GROUPS["Nautobot Engineer"]],
        "enabled": True,
        "app_label": ["extras"],
        "model": ["objectmetadata"],
    },
    {
        "name": "object_metadata_va",
        "actions": ["view", "add"],
        "groups": [],
        "enabled": True,
        "app_label": ["extras"],
        "model": ["objectmetadata"],
    },
    {
        "name": "object_metadata_vac",
        "actions": ["view", "add", "change"],
        "groups": [],
        "enabled": True,
        "app_label": ["extras"],
        "model": ["objectmetadata"],
    },
    {
        "name": "object_metadata_vacd",
        "actions": ["view", "add", "change", "delete"],
        "groups": [GROUPS["Nautobot Architect"]],
        "enabled": True,
        "app_label": ["extras"],
        "model": ["objectmetadata"],
    },
]


def create_permissions(delta):
    created = 0
    skipped = 0

    for entry in delta:
        name = entry["name"]

        if ObjectPermission.objects.filter(name=name).exists():
            print(f"  SKIP      {name} (already exists)")
            skipped += 1
            continue

        object_types = []
        for app_label, model in zip(entry["app_label"], entry["model"]):
            try:
                ct = ContentType.objects.get(app_label=app_label, model=model)
                object_types.append(ct)
            except ContentType.DoesNotExist:
                print(f"  WARNING: ContentType '{app_label} | {model}' not found — skipping {name}")
                continue

        perm = ObjectPermission.objects.create(
            name=name,
            actions=entry["actions"],
            enabled=entry["enabled"],
        )
        perm.object_types.set(object_types)
        perm.groups.set(entry["groups"])

        print(f"  CREATED   {name}")
        created += 1

    print(f"\nDone. {created} permissions created, {skipped} skipped.")


create_permissions(delta=DELTA)
